### ISSUE TITLE
After running install command, does not leave the terminal and is writing messages in the log

### ISSUE THREAD

**Issue by addodelgrossi** [jaspeen/oracle-11g#1]
The message displayed in the log, but does not end the process

```
listener: 08-OCT-2015 03:31:39 * service_update * orcl * 0
listener: Thu Oct 08 03:32:09 2015
listener: 08-OCT-2015 03:32:09 * service_update * orcl * 0
listener: Thu Oct 08 03:32:09 2015
listener: 08-OCT-2015 03:32:09 * service_update * orcl * 0
```

Thanks

**Comment by co2y** [comment]
same questions

**Comment by jaspeen** [comment]
That's because without -d option container runs in foreground mode. This oracle alert log and logs from listener.
When -d option specified for docker run command it will start in background and these logs can be viewed via docker logs <container>.
Command in description on docker hub fixed some time ago.
